-- =============================================
-- BASE DE DATOS MINISUPER
-- =============================================

-- 1. METODO DE PAGO
CREATE TABLE metodo_pago(
    id_metodo_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE,
    descripcion VARCHAR2(100)
);

-- 2. ROL
CREATE TABLE rol(
    id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE,
    descripcion VARCHAR2(100)
);

-- 3. CLIENTE
CREATE TABLE cliente(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    cedula VARCHAR2(20) NOT NULL UNIQUE,
    telefono VARCHAR2(15),
    correo VARCHAR2(80) UNIQUE
);

-- 4. PROVEEDOR
CREATE TABLE proveedor(
    id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    correo VARCHAR2(80) UNIQUE,
    direccion VARCHAR2(200)
);

-- 5. CATEGORIA
CREATE TABLE categoria(
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(100)
);

-- 6. USUARIO
CREATE TABLE usuario(
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    correo VARCHAR2(80) NOT NULL UNIQUE,
    contrasena VARCHAR2(100) NOT NULL,
    estado BOOLEAN DEFAULT TRUE NOT NULL,
    id_rol NUMBER NOT NULL,
    CONSTRAINT fk_usuario_rol FOREIGN KEY(id_rol) REFERENCES rol(id_rol)
);

-- 7. PRODUCTO
CREATE TABLE producto(
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    codigo_barras VARCHAR2(20) UNIQUE,
    descripcion VARCHAR2(150),
    precio_compra NUMBER(10,2) NOT NULL CHECK(precio_compra >= 0),
    precio_venta NUMBER(10,2) NOT NULL CHECK(precio_venta >= 0),
    estado BOOLEAN DEFAULT TRUE NOT NULL,
    id_categoria NUMBER NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY(id_categoria) REFERENCES categoria(id_categoria),
    CONSTRAINT chk_precio CHECK(precio_venta >= precio_compra)
);

-- 8. INVENTARIO
CREATE TABLE inventario(
    id_inventario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL UNIQUE,
    cantidad_disponible NUMBER(10) DEFAULT 0 NOT NULL CHECK(cantidad_disponible >= 0),
    cantidad_minima NUMBER(10) DEFAULT 0 NOT NULL CHECK(cantidad_minima >= 0),
    ultima_actualizacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_inventario_producto FOREIGN KEY(id_producto) REFERENCES producto(id_producto)
);

-- 9. VENTA
CREATE TABLE venta(
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(12,2) NOT NULL CHECK(total >= 0),
    id_usuario NUMBER NOT NULL,
    id_cliente NUMBER,
    id_metodo_pago NUMBER NOT NULL,
    CONSTRAINT fk_venta_usuario FOREIGN KEY(id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_venta_cliente FOREIGN KEY(id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_metodo_pago_venta FOREIGN KEY(id_metodo_pago) REFERENCES metodo_pago(id_metodo_pago)
);

-- 10. DETALLE DE VENTA
CREATE TABLE detalle_venta(
    id_detalle_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMBER(10) NOT NULL CHECK(cantidad > 0),
    precio_unitario NUMBER(10,2) NOT NULL CHECK(precio_unitario >= 0),
    subtotal NUMBER(12,2) NOT NULL CHECK(subtotal >= 0),
    id_producto NUMBER NOT NULL,
    id_venta NUMBER NOT NULL,
    CONSTRAINT fk_detalle_venta_producto FOREIGN KEY(id_producto) REFERENCES producto(id_producto),
    CONSTRAINT fk_detalle_venta_venta FOREIGN KEY(id_venta) REFERENCES venta(id_venta)
);

-- 11. COMPRA
CREATE TABLE compra(
    id_compra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(12,2) NOT NULL CHECK(total >= 0),
    id_proveedor NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    CONSTRAINT fk_compra_proveedor FOREIGN KEY(id_proveedor) REFERENCES proveedor(id_proveedor),
    CONSTRAINT fk_compra_usuario FOREIGN KEY(id_usuario) REFERENCES usuario(id_usuario)
);

-- 12. DETALLE DE COMPRA
CREATE TABLE detalle_compra(
    id_detalle_compra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER(10) NOT NULL CHECK(cantidad > 0),
    precio_unitario NUMBER(10,2) NOT NULL CHECK(precio_unitario >= 0),
    subtotal NUMBER(12,2) NOT NULL CHECK(subtotal >= 0),
    CONSTRAINT fk_detalle_compra_compra FOREIGN KEY(id_compra) REFERENCES compra(id_compra),
    CONSTRAINT fk_detalle_compra_producto FOREIGN KEY(id_producto) REFERENCES producto(id_producto)
);

-- 13. BITACORA
CREATE TABLE bitacora(
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    accion VARCHAR2(20) NOT NULL,
    tabla_afectada VARCHAR2(30) NOT NULL,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    detalle VARCHAR2(200),
    CONSTRAINT fk_bitacora_usuario FOREIGN KEY(id_usuario) REFERENCES usuario(id_usuario)
);

-- =============================================
-- DATOS INICIALES
-- =============================================
INSERT INTO rol(nombre, descripcion) VALUES('Administrador', 'Acceso total al sistema');
INSERT INTO rol(nombre, descripcion) VALUES('Cajero', 'Solo ventas y consultas');

INSERT INTO metodo_pago(nombre, descripcion) VALUES('Efectivo', 'Pago en caja');
INSERT INTO metodo_pago(nombre, descripcion) VALUES('Tarjeta', 'Debito o credito');
INSERT INTO metodo_pago(nombre, descripcion) VALUES('SINPE Movil', 'Transferencia movil');

INSERT INTO usuario(nombre, correo, contrasena, estado, id_rol) VALUES('Admin', 'admin@minisuper.com', 'admin123', TRUE, 1);

COMMIT;